name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  default_tools:
    name: Test default system tools
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2022, macos-latest, ubuntu-latest ]

    steps:
        - uses: actions/checkout@v3
        - uses: mlugg/setup-zig@v1
          with:
            version: 0.13.0-dev.351+64ef45eb0
        - run: zig version
        - run: zig build test --summary all